version: "3.7"
services:
    digiserver:
        db:
            image: digiserver:1.0
            environment: 
                DATABASE_PATH: './digidatabase.db'
            ports:
                - "3001:8080"
            volumns:
                - ./:/usr/src/app